### ISSUE TITLE
 Counting Difference in Ajax Call and Form Submission

### ISSUE THREAD

**Issue by kashifumar** [instasent/sms-counter-php#22]
I am facing a very strange issue. When I pass the text via an ajax call, I get the count of the message as 1 sms but when the same text is submitted via a form, I get it as 2 sms count, The total length in first case it says 158 characters and on form submission it says 162 characters, The text is the following. I am really stuck in this and the whole system is stuck due to this. Any help is much appreciated

EID-UL-ADHA SPECIAL
FLAT 10% OFF on stitching and fabrics.
Place your order today at your nearest Dandy and get it before Eid.
03111132639
www.dandydesigns.pk

Sorry for the link the comment but thats part of the sms I am having problem with

**Comment by luishdez** [comment]
Check the encoding that uses the form vs ajax request. And check for breaklines at the end. If you'r using windows it's most likely that it's adding an extra para of chars.  Use common technics of debugging. Dump the content in your backend etc.

I'm closing this issue since likely it's a problem in your encoding  and code. In case you discover it's a bug I'll re-open.
